apiVersion: v1
kind: Service
metadata:
  namespace: compage_module_bheem
  labels:
    app: compage_module_bheem
  name: compage_module_bheem
spec:
  ports:
  
    - protocol: TCP
      port: 1234
      targetPort: 1234
   
   
  selector:
    app: compage_module_bheem
  type: ClusterIP
